"use server";

import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/server";
import { v4 as uuidv4 } from "uuid";

export async function placeOrder(formData: FormData) {
  const supabase = await createClient();
  const supabaseAdmin = await createAdminClient();
  
  const storeId = formData.get("storeId") as string;
  const customerName = formData.get("customerName") as string;
  const customerEmail = formData.get("customerEmail") as string;
  const customerPhone = formData.get("customerPhone") as string;
  const shippingMethod = formData.get("shippingMethod") as string;
  const shippingFee = parseFloat(formData.get("shippingFee") as string) || 0;
  const shippingAddress = formData.get("shippingAddress") as string;
  const shippingCity = formData.get("shippingCity") as string;
  const shippingState = formData.get("shippingState") as string;
  const rawPaymentMethod = formData.get("paymentMethod") as string;
  const paymentMethod = rawPaymentMethod === "transfer" ? "bank_transfer" : "cash_on_delivery";
  const subtotalAmount = parseFloat(formData.get("subtotalAmount") as string) || 0;
  const totalAmount = parseFloat(formData.get("totalAmount") as string) || 0;
  const items = JSON.parse(formData.get("items") as string || "[]");
  const receiptFile = formData.get("receiptFile") as File | null;
  
  if (!storeId || !customerName || !customerEmail || items.length === 0) {
    return { success: false, error: "Missing required information" };
  }

  const { data: store } = await supabase.from("stores").select("whatsapp_number, slug").eq("id", storeId).single();
  
  let paymentReceiptUrl = null;
  if (receiptFile) {
    const fileExt = receiptFile.name.split('.').pop();
    const fileName = `${uuidv4()}.${fileExt}`;
    const filePath = `${storeId}/receipts/${fileName}`;
    
    // We use the admin client since the guest user does not have permission to upload
    const { error: uploadError } = await supabaseAdmin.storage
      .from("store-assets")
      .upload(filePath, receiptFile);

    if (uploadError) {
      console.error("Receipt upload error:", uploadError);
      return { success: false, error: "Failed to upload payment receipt." };
    }
    
    const { data: { publicUrl } } = supabaseAdmin.storage
      .from("store-assets")
      .getPublicUrl(filePath);
      
    paymentReceiptUrl = publicUrl;
  }

  // order_number is generated by trigger
  const { data: order, error } = await supabase.from("orders").insert({
    store_id: storeId,
    customer_name: customerName,
    customer_email: customerEmail,
    customer_phone: customerPhone,
    shipping_method: shippingMethod as any,
    shipping_fee: shippingFee,
    shipping_address: shippingAddress,
    shipping_city: shippingCity,
    shipping_state: shippingState,
    payment_method: paymentMethod as any,
    subtotal_amount: subtotalAmount,
    total_amount: totalAmount,
    status: 'pending',
    payment_receipt_url: paymentReceiptUrl,
  }).select().single();

  if (error) return { success: false, error: error.message };

  // Insert items
  const orderItems = items.map((item: any) => ({
    order_id: order.id,
    product_id: item.productId,
    product_name: item.name,
    variant_label: item.variantLabel,
    quantity: item.quantity,
    unit_price: item.price,
    total_price: item.price * item.quantity,
  }));

  const { error: itemsError } = await supabase.from("order_items").insert(orderItems);
  if (itemsError) return { success: false, error: itemsError.message };
  
  const token = Math.random().toString(36).substring(2, 12); // nanoid(10) equivalent

  // Build WhatsApp Message
  const waMessage = `New Order: ${order.order_number}\nName: ${customerName}\nTotal: NGN ${totalAmount}`;
  const whatsappUrl = store?.whatsapp_number ? `https://wa.me/${store.whatsapp_number}?text=${encodeURIComponent(waMessage)}` : null;

  return { 
    success: true, 
    orderId: order.id, 
    trackingToken: token,
    whatsappUrl 
  };
}
