"use server";

import { createClient, createAdminClient } from "@/lib/supabase/server";
import { v4 as uuidv4 } from "uuid";

export async function placeOrder(formData: FormData) {
  const supabase = await createClient();
  const supabaseAdmin = await createAdminClient();
  
  const storeId = formData.get("storeId") as string;
  const customerName = formData.get("customerName") as string;
  const customerEmail = formData.get("customerEmail") as string;
  const customerPhone = formData.get("customerPhone") as string;
  const shippingMethod = formData.get("shippingMethod") as string;
  const shippingFee = parseFloat(formData.get("shippingFee") as string) || 0;
  const shippingAddress = formData.get("shippingAddress") as string;
  const shippingCity = formData.get("shippingCity") as string;
  const shippingState = formData.get("shippingState") as string;
  const rawPaymentMethod = formData.get("paymentMethod") as string;
  const paymentMethod = rawPaymentMethod === "transfer" ? "bank_transfer" : "cash_on_delivery";
  const subtotalAmount = parseFloat(formData.get("subtotalAmount") as string) || 0;
  const totalAmount = parseFloat(formData.get("totalAmount") as string) || 0;
  const items = JSON.parse(formData.get("items") as string || "[]");
  const receiptFile = formData.get("receiptFile") as File | null;
  
  if (!storeId || !customerName || !customerEmail || !customerPhone || items.length === 0) {
    return { success: false, error: "Missing required information" };
  }

  // Validate email format server-side
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  if (!emailRegex.test(customerEmail)) {
    return { success: false, error: "Invalid email address" };
  }

  const { data: store } = await supabase.from("stores").select("whatsapp_number, slug, subscription_plan").eq("id", storeId).single();
  if (!store) {
    return { success: false, error: "Store not found" };
  }

  // Check order limits
  if (store.subscription_plan) {
    const { data: plan } = await supabase.from("plans").select("order_limit").ilike("name", store.subscription_plan).single();
    if (plan && plan.order_limit !== -1) {
      const startOfMonth = new Date(new Date().getFullYear(), new Date().getMonth(), 1).toISOString();
      const { count } = await supabase.from("orders").select("id", { count: "exact", head: true }).eq("store_id", storeId).gte("created_at", startOfMonth);
      
      if (count !== null && count >= plan.order_limit) {
        return { success: false, error: "This store cannot accept new orders at this time. Please contact the seller directly." };
      }
    }
  }

  // --- Idempotency guard: prevent duplicate orders within a 60-second window ---
  const sixtySecondsAgo = new Date(Date.now() - 60_000).toISOString();
  const { data: recentOrder } = await supabase
    .from("orders")
    .select("id")
    .eq("store_id", storeId)
    .eq("customer_email", customerEmail)
    .eq("total_amount", totalAmount)
    .gte("created_at", sixtySecondsAgo)
    .limit(1)
    .maybeSingle();

  if (recentOrder) {
    // Return the existing order id so the client can still redirect correctly
    return { success: true, orderId: recentOrder.id, trackingToken: null, whatsappUrl: null, duplicate: true };
  }
  // --- End idempotency guard ---
  
  let paymentReceiptUrl = null;
  if (receiptFile && receiptFile.size > 0) {
    // Validate file type — only allow common receipt image/PDF types
    const allowedMimeTypes = ["image/jpeg", "image/png", "image/webp", "application/pdf"];
    if (!allowedMimeTypes.includes(receiptFile.type)) {
      return { success: false, error: "Invalid file type. Only JPG, PNG, WEBP, or PDF receipts are allowed." };
    }

    // Validate file size — max 5MB
    const MAX_FILE_SIZE = 5 * 1024 * 1024; // 5MB
    if (receiptFile.size > MAX_FILE_SIZE) {
      return { success: false, error: "Receipt file is too large. Maximum size is 5MB." };
    }

    const fileExt = receiptFile.type === "application/pdf" ? "pdf" : receiptFile.type.split("/")[1];
    const fileName = `${uuidv4()}.${fileExt}`;
    const filePath = `${storeId}/receipts/${fileName}`;
    
    const { error: uploadError } = await supabaseAdmin.storage
      .from("store-assets")
      .upload(filePath, receiptFile, { cacheControl: '3600', upsert: false });

    if (uploadError) {
      console.error("Receipt upload error:", uploadError);
      return { success: false, error: "Failed to upload payment receipt." };
    }
    
    const { data: { publicUrl } } = supabaseAdmin.storage
      .from("store-assets")
      .getPublicUrl(filePath);
      
    paymentReceiptUrl = publicUrl;
  }

  // order_number is generated by trigger
  const { data: order, error } = await supabase.from("orders").insert({
    store_id: storeId,
    customer_name: customerName,
    customer_email: customerEmail,
    customer_phone: customerPhone,
    shipping_method: shippingMethod as any,
    shipping_fee: shippingFee,
    shipping_address: shippingAddress,
    shipping_city: shippingCity,
    shipping_state: shippingState,
    payment_method: paymentMethod as any,
    subtotal_amount: subtotalAmount,
    total_amount: totalAmount,
    status: 'pending',
    payment_receipt_url: paymentReceiptUrl,
  }).select().single();

  if (error) return { success: false, error: error.message };

  // --- Pre-order stock validation ---
  for (const item of items) {
    if (!item.productId) continue;
    const { data: stockCheck } = await supabase
      .from("products")
      .select("stock_quantity, name")
      .eq("id", item.productId)
      .single();

    if (stockCheck && stockCheck.stock_quantity !== null) {
      if (stockCheck.stock_quantity <= 0) {
        return { success: false, error: `"${stockCheck.name}" is out of stock.` };
      }
      if (item.quantity > stockCheck.stock_quantity) {
        return {
          success: false,
          error: `Only ${stockCheck.stock_quantity} unit(s) of "${stockCheck.name}" are available.`,
        };
      }
    }
  }
  // --- End stock validation ---

  // Insert items — recompute prices server-side from DB to prevent price manipulation
  let serverSubtotal = 0;
  const orderItems = [];
  for (const item of items) {
    if (!item.productId) continue;
    const { data: dbProduct } = await supabase
      .from("products")
      .select("name, price")
      .eq("id", item.productId)
      .single();
    if (!dbProduct) return { success: false, error: `Product not found: ${item.name}` };
    const qty = Math.max(1, parseInt(item.quantity) || 1);
    const lineTotal = dbProduct.price * qty;
    serverSubtotal += lineTotal;
    orderItems.push({
      order_id: order.id,
      product_id: item.productId,
      product_name: dbProduct.name,
      variant_label: item.variantLabel || null,
      quantity: qty,
      unit_price: dbProduct.price,
      total_price: lineTotal,
    });
  }

  const { error: itemsError } = await supabase.from("order_items").insert(orderItems);
  if (itemsError) return { success: false, error: itemsError.message };

  // --- Deduct stock quantity and auto-deactivate when stock hits 0 ---
  for (const item of items) {
    if (!item.productId) continue;

    const { data: product } = await supabase
      .from("products")
      .select("stock_quantity")
      .eq("id", item.productId)
      .single();

    if (product && product.stock_quantity !== null) {
      const newQty = Math.max(0, product.stock_quantity - item.quantity);
      const updatePayload: Record<string, any> = { stock_quantity: newQty };

      // Auto-deactivate when out of stock so seller is notified via Inactive badge
      if (newQty === 0) {
        updatePayload.is_published = false;
      }

      await supabase
        .from("products")
        .update(updatePayload)
        .eq("id", item.productId);
    }
  }
  // --- End stock deduction ---
  
  const token = Math.random().toString(36).substring(2, 12); // nanoid(10) equivalent

  // Build WhatsApp Message
  const waMessage = `New Order: ${order.order_number}\nName: ${customerName}\nTotal: NGN ${totalAmount}`;
  const whatsappUrl = store?.whatsapp_number ? `https://wa.me/${store.whatsapp_number}?text=${encodeURIComponent(waMessage)}` : null;

  return { 
    success: true, 
    orderId: order.id, 
    trackingToken: token,
    whatsappUrl 
  };
}
